preview_root := ~/.vim/preview

all : $(preview_root)/ft/dot/preview.vim $(preview_root)/ft/c/preview.vim $(preview_root)/ft/r/preview.vim $(preview_root)/ft/plaintex/preview.vim

$(preview_root)/ft/dot/preview.vim : dot/preview.vim
	install -m 0644 -D $< $@
$(preview_root)/ft/c/preview.vim   : c/preview.vim
	install -m 0644 -D $< $@
$(preview_root)/ft/r/preview.vim   : r/preview.vim
	install -m 0644 -D $< $@
$(preview_root)/ft/plaintex/preview.vim : plaintex/*
	install -m 0644 -D $^ ${@D}
